name: AiTrend Issue æ¨¡æ¿
contact_links:
  - name: ğŸ“– æ–‡æ¡£
    url: https://github.com/Lychee-AI-Team/AiTrend/tree/main/docs
    about: æŸ¥çœ‹é¡¹ç›®æ–‡æ¡£
  - name: ğŸ’¬ è®¨è®º
    url: https://github.com/Lychee-AI-Team/AiTrend/discussions
    about: åœ¨ Discussions ä¸­æé—®
